### ISSUE TITLE
The instrument version (3.1) does not support the API

### ISSUE THREAD

**Issue by massfrontier** [thermofisherlsms/iapi#10]
Hi,
We have installed Orbitrap Fusion 3.1.2162.0. Unfortunately we are getting exception "The instrument version (3.1) does not support the API".

Is there anything we can do to fix this?

Thanks

**Comment by jacobrayschwartz** [comment]
Hi,

Have you installed the API license for 3.1? This is done via Tune and is required before being able to use the API.

Jacob

**Comment by massfrontier** [comment]
Hi Jacob
We believe we have license applied properly
![licencse](https://user-images.githubusercontent.com/19347655/32717906-ae0c44c6-c85b-11e7-80ce-6eb355e22854.png)

**Comment by jacobrayschwartz** [comment]
Ah, I see now. There was an issue in that release that we didn't see due to development environments. It's been fixed in the latest build. Sorry about the confusion. I'll get the build uploaded for you.
