### ISSUE TITLE
Add support for BoxCar style acquisition

### ISSUE THREAD

**Issue by chhh** [thermofisherlsms/iapi#15]
Allow setting multiple custom isolation windows and corresponding injection times for the quadrupole.

**Comment by dbaileychess** [comment]
This is in the works.

**Comment by jesse-canterbury** [comment]
If I understand correctly, this was enabled as of Tune version 3.5.  See [changelog.md](url); for each window you can supply a target like so:

scan.Values["PrecursorMass"] = "195,524,1522";
scan.Values["IsolationWidth"] = "5,5,5";
**scan.Values["MSXTargets"] = "1000,10000,100000";**
