### ISSUE TITLE
Add capability to define "Scan Description" as a custom string

### ISSUE THREAD

**Issue by chhh** [thermofisherlsms/iapi#16]
This is very useful for debugging custom methods, e.g. to figure out which why did I schedule that custom scan in the first place.

**Comment by dbaileychess** [comment]
Yes, this would be a useful addition to the API. It supports up to a maximum of 20-characters, will that be sufficient for your needs?

**Comment by chhh** [comment]
Having 20 chars is better than having no chars :)

**Comment by jesse-canterbury** [comment]
This is now working for Tribrids in Tune version 4.0.  You can add a scan description by doing 
scan.Values["ScanDescription"] = "MyScan";

You only get 16 characters though, not the previously mentioned 20.  :)  

This will be more properly documented soon.
