### ISSUE TITLE
Icentroid isMonoisotopic always null

### ISSUE THREAD

**Issue by courcelm** [thermofisherlsms/iapi#17]
Hello,

Is Icentroid isMonoisotopic working? It is always null.

**Comment by dbaileychess** [comment]
The field is not supported at the moment. We are exploring adding this, and the other not yet implemented fields, in future releases.

**Comment by jesse-canterbury** [comment]
This is now fixed, for tribrids at least, in Tune version 4.0.  If this is still an issue on Exploris or Exactive systems, please open a new issue with updated information.
