### ISSUE TITLE
Question - Fusion quadrupole isolation

### ISSUE THREAD

**Issue by chhh** [thermofisherlsms/iapi#18]
If I do an MS1 scan in orbi is the quadrupole used to filter out the ions that are outside the scan mass range?
Will the instrument behave differently if I do the following two scans:
```
["Analyzer" => "Orbitrap", "FirstMass" => 800, "LastMass" => 1000, "IsolationMode" => "None"]
["Analyzer" => "Orbitrap", "FirstMass" => 800, "LastMass" => 1000, "IsolationMode" => "Quadrupole"]
```

**Comment by dbaileychess** [comment]
When you specify 'Quadrupole' isolation, the quad will be switched to resolving mode and isolate the given mass range (FirstMass, LastMass). When the option is set to 'None', the quad is in RF-only mode and passes  all masses through.
