### ISSUE TITLE
64 bit support

### ISSUE THREAD

**Issue by rfellers** [thermofisherlsms/iapi#2]
(Build 2.2.80) Our application requires the ability to cache more than the 32 bit .NET limit in order to speed up data processing during acquisition.

**Comment by dbaileychess** [comment]
This is still in discussion, as our main Tune application is not 64-bit enabled at the moment, the API is also forced to be 32-bit.

**Comment by massfrontier** [comment]
Any updates on this feature?

**Comment by dbaileychess** [comment]
We don't have any immediate plans to support a native 64-bit. I will be moving this to Future and will update accordingly.

**Comment by joewandy** [comment]
Hi @dbaileychess thank you for your hard work on IAPI! 

I wonder if there has been any update on this issue since 2018?

**Comment by jesse-canterbury** [comment]
Hi, thanks for bumping this issue!  The version of Fusion.API-1.0.dll that's currently uploaded here was built for the "Any CPU" configuration, so it should work with your 64-bit applications.  If you need one that's built explicitly under the "x64" configuration, please let us know.

**Comment by jesse-canterbury** [comment]
I'm going to close this issue now, as 64-bit functionality should now be supported.  If anyone continues to have problems of this sort, please open a new issue.  Thanks!
