### ISSUE TITLE
Question - What's the difference between API 1.0 + API 1.1 and API 2.0?

### ISSUE THREAD

**Issue by chhh** [thermofisherlsms/iapi#20]
What's the difference between API 1.0 + API 1.1 and API 2.0?

**Comment by dbaileychess** [comment]
API 1.0 and 1.1 are for the Q-Exactive series. 1.1 is a pure superset of 1.0.

API 2.0 is for the Fusion series. API 2.0 is not a pure superset of 1.1, but it does follow the basic scheme of the 1.X series APIs.
