### ISSUE TITLE
Question: Tune compatibility

### ISSUE THREAD

**Issue by jylanwhu** [thermofisherlsms/iapi#24]
Hi, I would like to install the IAPI for our QE Plus (Tune v2.9), is the current IAPI supporting that Tune version?

Thanks & best,
Jiayi

**Comment by jesse-canterbury** [comment]
Very sorry for the extended delay!  As far as I know, the IAPI should be supported in current QE Tune versions.   

Closing this now as obsolete.  If it's still a problem, please feel free to open a new issue with updated information.
