### ISSUE TITLE
tribrid method-filter example not updated?

### ISSUE THREAD

**Issue by jessicawang025** [thermofisherlsms/iapi#28]
AcquisitionStreamOpening and AcquisitionStreamClosing are not defined in IFusionMsScanContainer in the **tribrid method-filter example** (errors in lines 107, 108). 

MsAcquisitionOpeningEventArgs also couldn't be found (line 116).

**Comment by jesse-canterbury** [comment]
You are correct, this example has not been updated in some time.  I'll be revising the IAPI examples in the coming weeks in order to align with more recent developments.  Hopefully after that this example will work for you.  I'll leave this open until then.

**Comment by jesse-canterbury** [comment]
Greetings again.  It appears these build errors are easily corrected.  MsAcquisitionOpeningEventArgs should be changed to AcquisitionOpeningEventArgs (i.e. remove the first two letters).  Similarly, AcquisitionStreamOpening and AcquisitionStreamClosing are defined in the InstAcq, so you can change it to this:

![image](https://user-images.githubusercontent.com/19335425/124837774-66c1b480-df3a-11eb-9920-8f831354ffec.png)

This should allow the project to build.  I will be updating the examples soon with these corrections, but hopefully this will allow you to get going.

**Comment by jesse-canterbury** [comment]
Closing this now since the original issue was fixed.
