### ISSUE TITLE
Controlling FAIMS on Exploris

### ISSUE THREAD

**Issue by chhh** [thermofisherlsms/iapi#33]
Hi, is it possible to set FAIMS values on Exploris?
`InstrumentValues` says there are no commands available for this node.
I also used the example from this repository and I don't get any notifications when I change FAIMS cv from Tune. The only notification I'm getting is when I turn "FAIMS voltages" to On - then I get a notification about "Network Devices" node.

**Comment by KyowonJeong** [comment]
I also wonder if FAIMS cv could be controlled via iapi in Lumos or Eclipse machine. Is it not implemented yet? Then is it planned in the future? Please let me know..

**Comment by jesse-canterbury** [comment]
Yes, FAIMS can be controlled via the IAPI on tribrids.  The values to set are:  

1. "FAIMS CV" which can take values between -250 and 250V
2. "FAIMS Voltages" which can be set to either "On" or "Off"

**Comment by KyowonJeong** [comment]
> Yes, FAIMS can be controlled via the IAPI on tribrids. The values to set are:
> 
> 1. "FAIMS CV" which can take values between -250 and 250V
> 2. "FAIMS Voltages" which can be set to either "On" or "Off"

That is super!!! You just opened a gate for a brand new cool project! Thanks!!

**Comment by chhh** [comment]
> Yes, FAIMS can be controlled via the IAPI on tribrids. 

@jesse-canterbury Does that mean no luck for Exploris 480?

**Comment by jesse-canterbury** [comment]
@chhh Sorry for the delay.  I am still waiting on information from some colleagues to address your question.

**Comment by chhh** [comment]
@jesse-canterbury No luck yet?

**Comment by jesse-canterbury** [comment]
@chhh Sorry again for the delay.  Sorry to tell you that FAIMS control on Exploris is not supported via the IAPI.  It may be implemented in a future version, but no guarantees.
