### ISSUE TITLE
SPS scans

### ISSUE THREAD

**Issue by jpm369** [thermofisherlsms/iapi#36]
Is it possible to submit an SPS-MS3 scan through the API? It's not apparent from the PrecursorMass parameter how one might supply multiple precursors for a single MSn level.

**Comment by mammmals** [comment]
I believe you use `;` to separate MSn scan orders and `,` to separate SPS ions.
This can be tested in the `fusion example client`: https://github.com/thermofisherlsms/iapi/tree/master/examples/tribrid/fusion-example-client

**Comment by jpm369** [comment]
Ah, thanks Devin. That's exactly what I was looking for, couldn't find the syntax anywhere.
