### ISSUE TITLE
IAPI for Exploris 240?

### ISSUE THREAD

**Issue by JeffryDS** [thermofisherlsms/iapi#37]
Hi, thank you for the extremely useful information.
I am Interested in getting an IAPI online license on our instrument. 
We have an Orbitrap Exploris 240 with Tune Application 4.1. Is it possible to get an IAPI license for such instrument?

**Comment by jesse-canterbury** [comment]
Apologies, but in the Orbitrap Exploris line, the IAPI is only supported for the Exploris 480.
