### ISSUE TITLE
Event for Contact Closure

### ISSUE THREAD

**Issue by rfellers** [thermofisherlsms/iapi#4]
(Build 2.2.80) We would like to respond to contact closure events (from our LC) through the IAPI

**Comment by dbaileychess** [comment]
So when an external device sends a contact closure, you would like to receive that through the API?

**Comment by rfellers** [comment]
Ya, we'd like to start and stop our acquisition based on the contact closure.  Please let me know if this is crazy talk ...

**Comment by dbaileychess** [comment]
If you are going to run a method, there is now an option to have it wait for contact closure, just like you would from Tune/Xcalibur. Will this suffice for now, or do you want a dedicated event?

**Comment by rfellers** [comment]
I'm not sure if that will work with our current code.  We do everything through IScans.CreateCustomScan() as each scan could potentially be unique.  Is it possible to wrap that in a method?

**Comment by dbaileychess** [comment]
I guess I misspoke above. Any acquisition, either by method or just time/scans/continuous, has the option to be started on a contact closure event. 

I'll still explore if we can implement a dedicated event for it, as it may have other uses in the future.
