### ISSUE TITLE
Is it possible to start raw file recording from IAPI?

### ISSUE THREAD

**Issue by massfrontier** [thermofisherlsms/iapi#6]
We would like to have ability to manually start and stop recording of raw file. Is it possible?
Also picking raw file location as mentioned in #3 would be nice.

![capture](https://cloud.githubusercontent.com/assets/19347655/18608141/36f1ed76-7ce1-11e6-90e3-a6f1110aef44.PNG)

**Comment by dbaileychess** [comment]
Yes, this is being added to the API soon. You will be able to specify the rawfile location, (method file, time, # of scans) just like you would through Tune.

**Comment by dbaileychess** [comment]
Closed by a92cc1b3

**Comment by david-bouyssie** [comment]
Could you please add an example illustrating how to stop the current run and start the next one which was planned in the acquisition sequence?
