### ISSUE TITLE
HCD CollisionEnergy Problem

### ISSUE THREAD

**Issue by massfrontier** [thermofisherlsms/iapi#8]
I have trouble telling the instrument to take scan with ActivationType HCD and CollisionEnergy larger than 100. It seems like values larger than 100 are wrongly parsed and instrument takes HCD scan with CollisionEnergy 0 instead. 

IAPI outputs this to debug window : 
_2016-09-26 13:58:55.6271	Warn		Unapplied scan paremeter: (CollisionEnergy, 120)_
or
_2016-09-27 17:04:40.3204	Warn		Unapplied scan paremeter: (CollisionEnergy, 160.0)_

Should be easy fix, thanks :)

Orbitrap Fusion Lumos 2.2.116

**Comment by dbaileychess** [comment]
CID and HCD share the data portion of energies range, but I was validating it on the CID collision energy range 0-100% instead of the HCD range of 0-200%. Had to break the validation into CID/HCD specific logic.

Fixed in version 2.2.166.
