### ISSUE TITLE
ActivationQ parameter description

### ISSUE THREAD

**Issue by massfrontier** [thermofisherlsms/iapi#9]
I have spend few hours wondering why my ms3 scans are showing just a noise peaks when trying to obtain data by IAPI and doing same experiment by Tune was working fine.

Problem was the way I defined ActivationQ parameter. Description reads "ActivationQ | string | 0.25 | Activation Q (0.05-0.8)" which suggests its a single value parameter. It is not. You have too specify it for every ms stage(like a PrecursorMass).

If you wont specify it for every stage IAPI will probably use some other value ( my guess is 0.05) and it will result in different fragmentation behavior than in Tune.

No big deal, but maybe this message will save someones time :) 

Orbitrap Fusion Lumos 2.2.116

**Comment by dbaileychess** [comment]
Yes, it is a MS-stage dependent property. I fixed the Parameter description to indicate that. I'll also default the every stage (regardless of use) to 0.25.

Fixed in 2.2.166.
